let calendar = {
    "01/01":"If it thunders, a fast wind will blow, but not dangerous.",
    "01/02":"If it thunders, there will be unlooked-for war.",
    "01/03":"If it thunders, it shows after victory, loss for those in the war. Still, there will be plenty.",
    "01/04":"If it thunders, the common people will agree to make peace.",
    "01/05":"If it thunders, it signals health for the flocks.",
    "01/06":"If it thunders, it threatens a coughing sickness but signifies an abundance of fish and of fruits.",
    "01/07":"If it thunders, there will be a slave revolt and recurring illness.",
    "01/08":"If it thunders, the ruler of the state shall be in danger from the people.",
    "01/09":"If it thunders, the king of the East shall be in danger.",
    "01/10":"If it thunders, it signifies rapid movement of wind, and a plenty of grain, but a dearth of other crops.",
    "01/11":"If it thunders, it signals famine [reaching] just up to dumb animals.",
    "01/12":"If it thunders, men shall be damaged in their faces, but there will be much fodder [for horses/cattle], and a plenty of fish.",
    "01/13":"If it thunders, it threatens diseases.",
    "01/14":"If it thunders, it threatens need, and the creation/appearance of mice, and the slaughter of four-footed creatures.",
    "01/15":"If it thunders, servile revolt, and punishment for them, and abundance of crops.",
    "01/16":"If it thunders, the people shall be oppressed by the king.",
    "01/17":"If it thunders, it threatens nondangerous diseases.",
    "01/18":"If it thunders, affairs circulating abroad shall make the people rise up.",
    "01/19":"If it thunders, when the king will have victory, then  the common people will have the upper hand/stronger position.",
    "01/20":"If it thunders, there will be abundance of imported goods, but a coughing disease will afflict bodies.",
    "01/21":"If it thunders, the king hated by many shall be the object of a final plot.",
    "01/22":"If it thunders, there will be plenty, but also there will be an abundance of mice and of deer.",
    "01/23":"If it thunders, it signifies good order for the city.",
    "01/24":"If it thunders, it signifies disease following want.",
    "01/25":"If it thunders, there will be unrest among the slaves.",
    "01/26":"If it thunders, many shall be cut down by a man in power, but in the end he himself [will be killed].",
    "01/27":"If it thunders, it signifies nonthreatening diseases.",
    "01/28":"If it thunders, the fish of the sea shall be plentiful, but yet the flocks will be ruined by death.",
    "01/29":"If it thunders, the condition of the air oppressive, and disease-bearing for all.",
    "01/30":" If it thunders, it threatens plentiful death.",

    "02/01":"If it thunders, it threatens war and the ruin of wealthy men.",
    "02/02":"If it thunders, wheat in less supply, but barley better, and an increase in livestock, but there will be a wasting away of humans.",
    "02/03":"If it thunders, there will be civil unrest.",
    "02/04":"If it thunders, men shall be troubled not only in visage but also in their very minds.",
    "02/05":"If it thunders, there will be a large harvest, a destruction for men.",
    "02/06":"If it thunders, destruction of grain supplies and especially barley.",
    "02/07":"If it thunders, it threatens destruction though not for long to humans.",
    "02/08":"If it thunders, the greatest affair will inflame the state, and also fish will increase and yet dangerous wild beasts shall perish.",
    "02/09":"If it thunders, worse the barley.",
    "02/10":"If it thunders, the wild beasts shall undo the humans.",
    "02/11":"If it thunders, good deliveries [in childbirth] for women.",
    "02/12":"If it thunders, it threatens frequent death and unseasonable winds.",
    "02/13":"If it thunders, there will be plenty, yet at the same time, political unrest.",
    "02/14":"If it thunders, it threatens loss of progeny and an onslaught of poisonous reptiles.",
    "02/15":"If it thunders, the air shall carry plague, creation of both wild beasts and mice.",
    "02/16":"If it thunders, to the people, [it will be] auspicious,but of the powerful ones, bad [will come] out of discord.",
    "02/17":"If it thunders, summer will be most fruitful.",
    "02/18":"If it thunders, it threatens a heavy wind and eruption of pustules on bodies.",
    "02/19":"If it thunders, there will be a throng of reptiles and, in addition, of worms.",
    "02/20":"If it thunders, it signifies fine breezes.",
    "02/21":"If it thunders, it signifies abundance.",
    "02/22":"If it thunders, the air will be disease-carrying but not lethal.",
    "02/23":"If it thunders, it threatens deformity for men but destruction for birds.",
    "02/24":"If it thunders, it threatens good health for men but destruction for both fish and reptiles.",
    "02/25":"If it thunders, to those living luxuriously, a reversal. There will be wars and a heavy storm.",
    "02/26":"If it thunders, it threatens hot weather, and a lack of water, and scabs on bodies.",
    "02/27":"If it thunders, it signifies unrest among the commons.",
    "02/28":"If it thunders, it prophesies abundance, yet at the same time, a disease-giving wind will blow.",
    "02/29":"If it thunders, it signifies war and abundance.",
    "02/30":"If it thunders, it signifies good things with long duration after great divisions of the people.",
   
    "03/01":"If it thunders, for the entire year there will be strife and disagreements.",
    "03/02":"If it thunders, it shall end the threatening affairs.",
    "03/03":"If it thunders, for the state, discord following famine.",
    "03/04":"If it thunders, there will be boundless prosperity.",
    "03/05":"If it thunders, the spring will be sunny and the summer fruitful.",
    "03/06":"If it thunders, the same and even better.",
    "03/07":"If it thunders, a heavy wind will arise, which shall move the affairs of powerful men.",
    "03/08":"If it thunders, it signals rains.",
    "03/09":"If it thunders, it threatens ruin of man and creation of wild beasts.",
    "03/10":"If it thunders, destruction to the four-footed.",
    "03/11":"If it thunders, it signifies heavy rain and the creation of locusts.",
    "03/12":"If it thunders, a powerful man in politics or a general is endangered; on his behalf, battles will be waged, and the wild beasts shall fall upon man.",
    "03/13":"If it thunders, there will be plenty, but the wild beasts shall be destroyed, and the fish shall increase; and reptiles will trouble habitations but will not be harmful.",
    "03/14":"If it thunders, it signals prosperity but threatens a death of men and birth of wild beasts.",
    "03/15":"If it thunders, it signals hot spells and drought and a great throng of mice and fish.",
    "03/16":"If it thunders, healthful [will be] the year, yet lacking in necessities.",
    "03/17":"If it thunders, something unexpected will befall the people; ruin upon ruin for men and four-footed beasts.",
    "03/18":"If it thunders, it signifies a period of severe rain, and disease, and the birth of locusts, barrenness [of crops] near at hand.",
    "03/19":"If it thunders, a very dry summer and destructive.",
    "03/20":"If it thunders, man will live with better behavior at the same time as more prosperously.",
    "03/21":"If it thunders, it signifies prosperity after wars and hot spells causing destruction.",
    "03/22":"If it thunders, destruction of birds, but a plenty of daily supplies.",
    "03/23":"If it thunders, it signifies discord.",
    "03/24":"If it thunders, it signifies prosperity",
    "03/25":"If it thunders, new affairs are given birth among the people.",
    "03/26":"If it thunders, it announces [the] acquisition of imported slaves.",
    "03/27":"If it thunders, it signifies abundance imported from abroad.",
    "03/28":"If it thunders, there will be a plenty of marine fish.",
    "03/29":"If it thunders, the women shall obtain the better reputation.",
    "03/30":"If it thunders, there will be some powerful, selfpossessed man of the kingdom, through whom [will come] good cheer.",

    "04/01":"If it thunders, it threatens civil discord and the downfalls of fortunes.",
    "04/02":"If it thunders, sign of justice, bearing prosperity to good men, and paltry things to evil men.",
    "04/03":"If it thunders, it signifies profit out of a grain supply brought from abroad.",
    "04/04":"If it thunders, anger it threatens of those more powerful against the upright.",
    "04/05":"If it thunders, it signals a hot summer early [in the season] but a healthful year.",
    "04/06":"If it thunders, civil wars will arise.",
    "04/07":"If it thunders, it signifies all good things and a prosperous season.",
    "04/08":"If it thunders, it signifies heavy rains bearing disease.",
    "04/09":"If it thunders, it signifies victory for the kingdom and good cheer for the powerful ones.",
    "04/10":"If it thunders, of upright men there will be advances.",
    "04/11":"If it thunders, it signals the same things.",
    "04/12":"If it thunders, rains and prosperity and ruin of fish it signifies.",
    "04/13":"If it thunders, for men and for cattle destruction it threatens.",
    "04/14":"If it thunders, good health and prosperity it signifies.",
    "04/15":"If it thunders, it signals a plague.",
    "04/16":"If it thunders, it signifies abundance but at the same time the birth of field voles.",
    "04/17":"If it thunders, it signals a plenty of daily supplies.",
    "04/18":"If it thunders, it signals discord and thoughtlessness of men.",
    "04/19":"If it thunders, a powerful man in the state shall be deprived at once of both reputation and property.",
    "04/20":"If it thunders, it signals divine anger.",
    "04/21":"If it thunders, it signifies good fortune for the crops, yet war for the state.",
    "04/22":"If it thunders, it will be the destruction of the flies.",
    "04/23":"If it thunders, it signifies a rain helpful for the sprouting time.",
    "04/24":"If it thunders, there will be discord among those in power, but their plans will be exposed.",
    "04/25":"If it thunders, peace during the entire year.",
    "04/26":"If it thunders, it signifies great hope of fruits and scarcity of harvests.",
    "04/27":"If it thunders, omens from the sky incredibly shall be revealed.",
    "04/28":"If it thunders, by shields the people shall be saved.",
    "04/29":"If it thunders, zephyrus will prevail.",
    "04/30":"If it thunders, a shower of good things.",

    "05/01":"If it thunders, it signifies flight for the common people and loss of honor.",
    "05/02":"If it thunders, it threatens need.",
    "05/03":"If it thunders, it signifies abundance imported from abroad.",
    "05/04":"If it thunders, the air will be mild, and the crops will be plentiful.",
    "05/05":"If it thunders, there will be an interchange of hardships in political affairs, and wheat more plentiful than barley. The pulses, however, will be ruined.",
    "05/06":"If it thunders, it signifies that crops will ripen in haste and will be ruined.",
    "05/07":"If it thunders, there will be abundance of birds and fish.",
    "05/08":"If it thunders, ill-omened for the common people.",
    "05/09":"If it thunders, it signals plague, but not exceptionally life-threatening.",
    "05/10":"If it thunders, it announces storms, heavy rain, heavy floods of the rivers, a throng of lizards and of reptiles.",
    "05/11":"If it thunders, abundance to be hoped for both on land and sea.",
    "05/12":"If it thunders, there will be destruction of fish.",
    "05/13":"If it thunders, it signals an increase in river waters, but diseases for men.",
    "05/14":"If it thunders, there will be eastern war and great want.",
    "05/15":"If it thunders, it signifies abundance.",
    "05/16":"If it thunders, atonement must be made on account of terrible news.",
    "05/17":"If it thunders, it signifies rainy weather.",
    "05/18":"If it thunders, discord and out of it war and a lack of daily supplies.",
    "05/19":"If it thunders, through goodwill of the city, some man shall be exalted to the height of good fortune.",
    "05/20":"If it thunders, for those in the East, prosperity, but for those in the West, not the same.",
    "05/21":"If it thunders, atonement must be made on account of terrible news.",
    "05/22":"If it thunders, it signals heavy rains and destruction of marine fish.",
    "05/23":"If it thunders, it signifies a good and fruitful rain.",
    "05/24":"If it thunders, great evils such that those hearkening [to them] shall pass away from grief.",
    "05/25":"If it thunders, a hoped-for resting place and slackening of evils.",
    "05/26":"If it thunders, good for those working upon the tilled land.",
    "05/27":"If it thunders, there shall be prodigies, and a comet shall shine forth.",
    "05/28":"If it thunders, it shall be the same.",
    "05/29":"If it thunders, it signals northern war, but not dangerous for commerce.",
    "05/30":"If it thunders, the sprouting crops will be chilled by the winds.",
    
    "06/01":"If in any way it should thunder, there will be an abundance of fruits, with the exception of barley; but dangerous diseases will be inflicted upon bodies.",
    "06/02":"If in any way it should thunder, women in labor will have an easy delivery, but there will be abortion of cattle, yet there will be an abundance of fish.",
    "06/03":"If in any way it should thunder, there will be a scorching and drying wind, such that not only grains but even the soft fruits will be parched through and through and shrivel up.",
    "06/04":"If in any way it should thunder, the air will be cloudy and rainy, so that out of a moldy dampness the fruit cropswill rot.",
    "06/05":"If in any way it should thunder, ill-omened for the countryside. Those responsible for villages or towns will be thrown into a state of disorder.",
    "06/06":"If in any way it should thunder, just as the crops are maturing, some sort of wild pest that has sunk deep into them will waste them.",
    "06/07":"If in any way it should thunder, diseases will infect [men], but not many shall die. And while the cereal crops shall be successful, the soft fruits shall dry up.",
    "06/08":"If in any way it should thunder, it indicates wet weather and ruin of the grain.",
    "06/09":"If in any way it should thunder, there will be a loss of flocks through being overrun by wolves.",
    "06/10":"If in any way it should thunder, there will be frequent death, yet prosperity.",
    "06/11":"If in any way it should thunder, there will be days of heat, burning but harmless; there will be glad festivities in state affairs.",
    "06/12":"If in any way it should thunder, the same thing as on the preceding day.",
    "06/13":"If in any way it should thunder, it announces the fall of a ruler.",
    "06/14":" If in any way it should thunder, the atmosphere shall be burning hot, but there will be abundant harvest and good flow, not the poorest, of the river fish. Bodies, nevertheless, shall be utterly weak.",
    "06/15":"If in any way it should thunder, the feathered creatures shall be injured during the summer, and also the fishes shall perish.",
    "06/16":"If in any way it should thunder, it threatens not only dearth of the necessities of life but also war, while a prosperous man shall disappear from public life.",
    "06/17":" If in any way it should thunder, there shall be days of burning heat and destruction by mice, blind mice, and locusts. Still, it brings abundance and at the same time murders to the people.",
    "06/18":"If in any way it should thunder, it threatens destruction to the crops.",
    "06/19":"If in any way it should thunder, pests destructive to the crops shall perish.",
    "06/20":"If in any way it should thunder, it threatens discord for the community.",
    "06/21":"If in any way it should thunder, it means there will be a dearth of wine, but an increase in the other crops, and an abundance of fish.",
    "06/22":"If in any way it should thunder, the hot weather will be especially ruinous.", 
    "06/23":"If in any way it should thunder, it announces good cheer, a putting aside of ills, and an end to disease.",
    "06/24":"If in any way it should thunder, it announces plenty.",
    "06/25":"If in any way it should thunder, there will be wars and countless ills.",
    "06/26":"If in any way it should thunder, the winter will be especially harmful to the crops.",
    "06/27":"If in any way it should thunder, there is danger from the army for the men in power.",
    "06/28":"If in any way it should thunder, there will be a good harvest for the crops.",
    "06/29":"If in any way it should thunder, the affairs of the ruling city will be improved.",
    "06/30":"If in any way it should thunder, in a short time there shall be frequent death.",

    "07/01":"Upon the new moon, if in any way it should thunder, there shall be plenty, yet there shall be ruin of the flocks.",
    "07/02":"If in any way it should thunder, the late autumn will be good.",
    "07/03":"If in any way it should thunder, it signals a heavy winter.",
    "07/04":"If in any way it should thunder, the airs will be turbulent, so that of them will be born scarcity.",
    "07/05":"If in any way it should thunder, there will be an abundance of grain, yet it is the downfall of a virtuous ruler.",
    "07/06":"If in any way it should thunder, it threatens deathbearing diseases to the fortunes of slaves.",
    "07/07":"If in any way it should thunder, there will be rains harmful to the grain fields.",
    "07/08":"If in any way it should thunder, it signifies peace for the community, but ruin for the cattle herds, and a dry cough shall infect.",
    "07/09":"If in any way it should thunder, it foretells a vision of the gods and the advancement of many good men.",
    "07/10":"If in any way it should thunder, there will be lifesaving river waters.",
    "07/11":"If in any way it should thunder, it signals hot weather and stormy rain and a scarcity of grain.",
    "07/12":"If in any way it should thunder, there will be unexpected cold in the summer, because of which the necessities of life will be spoiled.",
    "07/13":"If in any way it should thunder, there will appear the most poisonous reptiles.",
    "07/14":"If in any way it should thunder, it shows one man will come to power over many. But this man is most unjust in state affairs.",
    "07/15":"If in any way it should thunder, there will be dissension among the common people and a scarcity of grain.",
    "07/16":"If in any way it should thunder, the king of the East . . . will be overcome [by?] war . . .5 and disease will be received from dry hot weather.",
    "07/17":"If in any way it should thunder, it signifies the succession of a great ruler.",
    "07/18":"If in any way it should thunder, it threatens a dearth of crops due to rainy weather.",
    "07/19":"If in any way it should thunder, it signifies war and the destruction of the powerful. On the other hand, there will be a plenty of cereals.",
    "07/20":"If in any way it should thunder, it threatens an unhealthy drought.",
    "07/21":"If in any way it should thunder, there will be disagreement among the subjects, but not for long.",
    "07/22":"If in any way it should thunder, it signals good things for the affairs of state, but for the bodies, diseases around the head.",
    "07/23":"If in any way it should thunder, the dissension of the common people will come to an end.",
    "07/24":"If in any way it should thunder, it shows the possible misfortune of a powerful man.",
    "07/25":"If in any way it should thunder, it will go badly for a band of youth and also for the crops along with them. It will be a disease-bearing time.",
    "07/26":"If in any way it should thunder, after great plenty there will be famine.",
    "07/27":"If in any way it should thunder, it threatens subcutaneous eruptions to [men’s] bodies.",
    "07/28":"If in any way it should thunder, there will be a dearth of water and a plague of poisonous reptiles.",
    "07/29":"If in any way it should thunder, it signifies a good harvest.",
    "07/30":"If in any way it should thunder, men bent on vengeance shall slip into the worst kind of treachery.",

    "08/01":"If in any way it should thunder, the affairs of the state will be slightly better, and there will be plenty.",
    "08/02":"If in any way it should thunder, it threatens both diseases and at the same time a dearth of the necessities of life.",
    "08/03":"If in any way it should thunder, it threatens both [public] trials and debates among the common people.",
    "08/04":"If in any way it should thunder, there will be a dearth of foodstuffs for both humans and dumb animals.",
    "08/05":"If in any way it should thunder, it signifies that the women are the more sagacious.",
    "08/06":"If in any way it should thunder, there will be an abundance of honey, yet a lack of both water and the other foodstuffs.",
    "08/07":"If in any way it should thunder, it signals harsh winds and diseases at the same time.",
    "08/08":"If in any way it should thunder, it threatens harmless disease to the four-footed.",
    "08/09":"If in any way it should thunder, it proclaims good health for men for a full year.",
    "08/10":"If in any way it should thunder, it threatens pains/suffering and wretchedness for the greater part of the people.",
    "08/11":"If in any way it should thunder, there will be a good harvest, yet the downfall of reptiles and harm to men.",
    "08/12":"If in any way it should thunder, there will be an abundance of cattle fodder and of acorns, but in the first ripening season, it will go badly.",
    "08/13":"If in any way it should thunder, there will be plague upon the bodies of both humans and dumb animals.",
    "08/14":"If in any way it should thunder, it signals war for all the people, yet an abundance of crops.",
    "08/15":"If in any way it should thunder, affairs will change for the worse.",
    "08/16":"If in any way it should thunder, it promises a deep peace.",
    "08/17":"If in any way it should thunder, the men of lowly degree shall be gloomy.",
    "08/18":"If in any way it should thunder, it threatens civil war.",
    "08/19":"If in any way it should thunder, the women and the servile class will dare to commit murders.",
    "08/20":"If in any way it should thunder, it threatens a plague on the cattle and disorder in the affairs of state.",
    "08/21":"If in any way it should thunder, it threatens at once prosperity and discord among the commons.",
    "08/22":"If in any way it should thunder, affairs will be moderately good for an entire year.",
    "08/23":"If in any way it should thunder, it signifies that the lightning bolt shall fall, and warns of slaughter",
    "08/24":"If in any way it should thunder, it threatens the loss of well-born youths.",
    "08/25":"If in any way it should thunder, it foretells that during a stormy winter there will be a shortage of tree fruits.",
    "08/26":"If in any way it should thunder, it signals war.",
    "08/27":"If in any way it should thunder, it threatens at once wars and treachery.",
    "08/28":"If in any way it should thunder, it signals both an abundance of crops and a loss by death of cattle.",
    "08/29":"If in any way it should thunder, it signals no sort of reversal.",
    "08/30":" If in any way it should thunder, it threatens diseases in the city over which it [the thunder] is cast down.",
    
    "09/01":"If in any way it should thunder, it signifies both a good harvest and good cheer.",
    "09/02":"If in any way it should thunder, there will be discord among the common people.",
    "09/03":"If in any way it should thunder, it signifies heavy rains and war.",
    "09/04":"If in any way it should thunder, it signifies the downfall of a powerful man and preparation for war.",
    "09/05":"If in any way it should thunder, it signifies an abundance of barley but a decrease in wheat.",
    "09/06":"If in any way it should thunder, there shall be power among the women greater than [what is] appropriate to their nature.",
    "09/07":"If in any way it should thunder, it threatens a disease and out of it, a disaster for the servile class.",
    "09/08":"If in any way it should thunder, it indicates that those especially powerful will consider crooked dealings in government, but they will not achieve their aims.",
    "09/09":"If in any way it should thunder, it threatens that a disease-bearing wind will blow.",
    "09/10":"If in any way it should thunder, there will be strife in the area in which the thunder is let loose; for another place [it is] not inapplicable.",
    "09/11":"If in any way it should thunder, the underlings of the well born will foment revolution in the state.",
    "09/12":"If in any way it should thunder, it says that the time of harvest shall be very rainy and there shall be famine.",
    "09/13":"If in any way it should thunder, it threatens grave famine.",
    "09/14":"If in any way it should thunder, it threatens diseases.",
    "09/15":"If in any way it should thunder, it signifies a wet spell, but at the same time, prosperity.",
    "09/16":"If in any way it should thunder, it is made known that there will be good sprouting, but [the plants will be] fruitless.",
    "09/17":"If it thunders, it threatens a lack of the necessities.",
    "09/18":"If it thunders, it signals both famine and wars.",
    "09/19":"If it thunders, the fruits of the trees will be successful, but there will be diseases and sedition among the commons",
    "09/20":"If it thunders, it threatens the destruction of a famous man and war.",
    "09/21":"If it thunders, it threatens ills and losses for the people.",
    "09/22":"If it thunders, it signals prosperity yet a heavy and wet winter.",
    "09/23":"If it thunders, it foretells a time of need during the winter of the year.",
    "09/24":"If it thunders, it threatens a drought. There will be an abundant harvest of the nut trees; around late autumn though, they will be destroyed by storms.",
    "09/25":"If it thunders, out of civil unrest a tyrant shall be raised up, and he will be undone, but the powerful will be destroyed utterly with insufferable penalties.",
    "09/26":"If it thunders, a corrupt ruler will be felled by divine decision.",
    "09/27":"If it thunders, powerful men will work hatred toward themselves and shall take sides against each other.",
    "09/28":"If it thunders, there will be signs revealing great things. Beware lest it pour rain upon the fire of joyful elation.",
    "09/29":"If it thunders, it threatens a severe drought.",
    "09/30":" If it thunders, affairs of state [shall change] from worse to better.",

    "10/01":"If it thunders, it threatens a corrupt tyrant over the affairs of state.",
    "10/02":"If it thunders, there will be prosperity but the destruction of the mice of dry land.",
    "10/03":"If it thunders, it signifies hurricanes and disturbances by which the trees will be overturned; there will be a great disruption in the affairs of common people.",
    "10/04":"If it thunders, the lower classes will have the upper hand over their betters, and the mildness of the air will be healthy.",
    "10/05":"If it thunders, there will be a surplus of all the necessities except grain.",
    "10/06":"If it thunders, appearance of future abundance, yet harvest will be less plentiful and autumn practically empty of fruit.",
    "10/07":"If it thunders, pulses will be plentiful but wine less.",
    "10/08":"If it thunders, an earthquake with roaring sound is to be expected.",
    "10/09":"If it thunders, it threatens destruction to wild beasts.",
    "10/10":"If it thunders, it signifies the downfall of a praiseworthy man.",
    "10/11":"If it thunders, it signifies a strange sort of wind will be of service to the pastures.",
    "10/12":"If it thunders, there will be prosperity, but wind squalls will oppress.",
    "10/13":"If it thunders, covenants/commerce will be good, and prosperity in addition. He who controls the government with heavy hand will not be strong for very long.",
    "10/14":"If it thunders, it threatens war and the loss of flocks to death.",
    "10/15":"If it thunders, there will be scarcity from a dry and searing wind falling upon the crops.",
    "10/16":"If it thunders, men will be weakened in such a manner that they will seem to be unrecognizable.",
    "10/17":"If it thunders, good fortune for a rich man and for men [who are] well born.",
    "10/18":"If it thunders, it signifies a plentiful grain supply brought in from foreign lands.",
    "10/19":"If it thunders, it warns of the downfall of a ruler or the overthrow of a king, but it warns of both discord among the common people and abundance.",
    "10/20":"If it thunders, it warns there will be a festering wound, and for the many, extreme suffering out of the discord.",
    "10/21":"If it thunders, there will be coughing sicknesses and oppression of the heart.",
    "10/22":"If it thunders, it threatens bad conditions and spotted diseases for the people.",
    "10/23":"If it thunders, the people will be of marvelously good cheer.",
    "10/24":"If it thunders, out of the discord of those in power, the common people will oppress [others].",
    "10/25":"If it thunders, there will be heavy misery resulting from misfortunes",
    "10/26":"If it thunders, there will be an increase of animals, but at the same time they will suffer thirst.",
    "10/27":"If it thunders, it signifies heavy rains.",
    "10/28":"If it thunders, there will be a dearth of the necessities.",
    "10/29":"If it thunders, a year of serious disease.",
    "10/30":". If it thunders, it signifies not merely prosperity, but even fewer enemies, and good cheer for the state.",
    
    "11/01":"If it thunders, it signifies discord for the city.",
    "11/02":"If it thunders, it foretells prosperity.",
    "11/03":"If it thunders, situations will pertain through which the lower classes will oppress [their] betters.",
    "11/04":"If it thunders, grain will be better.",
    "11/05":"If it thunders, it signifies storm for the state, and disease for humans and dumb animals alike.",
    "11/06":"If it thunders, borers will ruin the grain.",
    "11/07":"If it thunders, for those who are in the West, both humans and dumb beasts, diseases.",
    "11/08":"If it thunders, it says gluttony shall come about from menacing diseases.",
    "11/09":"If it thunders, the common people will be led into misery, but [there will be] an abundance of daily provisions.",
    "11/10":"If it thunders, for those in power, it makes an end to their perverted plans. A parching wind will wrack the trees.",
    "11/11":"If it thunders, men shall give blessings to the god, for the wind shall blow out of the East.",
    "11/12":"If it thunders, it indicates insomnia for some time for men.",
    "11/13":"If it thunders, a wealthy yet sickly period threatens, tormenting bodies with internal worms.",
    "11/14":"If it thunders, poisonous snakes shall somehow be gently undone by the men.",
    "11/15":"If it thunders, the fish will be especially plentiful, but it shall plague the water-bound beasts. The commonwealth rather better.",
    "11/16":"If it thunders, the creation of locusts and field voles, to the king, danger, and there will be an abundance of grain.",
    "11/17":"If it thunders, it signifies plentiful fodder for the flocks.",
    "11/18":"If it thunders, it signifies war and woes for city folk.",
    "11/19":"If it thunders, welfare of women.",
    "11/20":"If it thunders, it signifies famine not of long duration.",
    "11/21":"If it thunders, the mice shall perish; an abundance not merely of grain but also of pasturage, and a plenty of fishes.",
    "11/22":"If it thunders, it signifies a year of well-being.",
    "11/23":"If it thunders, disease-bearing wind will blow.",
    "11/24":"If it thunders, the watch-post shall complete for the state good service against enemy tricks.",
    "11/25":"If it thunders, there will be a very dangerous war.",
    "11/26":"If it thunders, it signifies a civil war and the death of many.",
    "11/27":"If it thunders, it threatens the same.",
    "11/28":"If it thunders, many of the councilmen of the wealthier rank shall be ruined utterly by cowardice.",
    "11/29":"If it thunders, the lower classes will do better, but the hoped-for fruit harvest shall be destroyed.",
    "11/30":"If it thunders, the mortals shall live in a condition more favored by the gods. Naturally, evils [will come] in due proportion.",

    "12/01":"If it thunders, it signifies a year of well-being corresponding to concord.",
    "12/02":"If it thunders, a plenty of fish and especially of fruits.",
    "12/03":"If it thunders, men will excessively consume their flocks because of a dearth of fish.",
    "12/04":"If it thunders, winter will be heavy, yet [there will be] abundance as well.",
    "12/05":"If it thunders, it threatens mangy diseases.",
    "12/06":"If it thunders, the men shall be visited with visions of the faces of the gods, they shall experience a bad outcome.",
    "12/07":"If it thunders, it signifies the same for all.",
    "12/08":"If it thunders, virulent disease; out of it, though, will be an abundance of crops, but a plague on the flocks.",
    "12/09":"If it thunders, there will be the downfall of a famous man.",
    "12/10":"If it thunders, it threatens slaughter for men from diseases, but the fish shall be abundant.",
    "12/11":"If it thunders, heat-bearing shall be the summer season, and plenty imported from foreign lands.",
    "12/12":"If it thunders, it threatens diseases from diarrhea.",
    "12/13":"If it thunders, plenty, yet diseases it threatens.",
    "12/14":"If it thunders, it signifies at the same time civil war and abundance.",
    "12/15":"If it thunders, many will set out for war, but few shall return.",
    "12/16":"If it thunders, newfangled affairs for the state.",
    "12/17":"If it thunders, it threatens that small locusts shall be born, yet there will still be plenty",
    "12/18":"If it thunders, there shall be a heavy war.",
    "12/19":"If it thunders, it threatens prolongation of war.",
    "12/20":"If it thunders, it tells a lack of the necessities.",
    "12/21":"If it thunders, it threatens a hot and disease-making wind will blow.",
    "12/22":"If it thunders, the summer will be hot but plentiful in crops.",
    "12/23":"If it thunders, it signifies a disease for men but a harmless one.",
    "12/24":"If it thunders, it threatens civil wars for the city and a plague on the beasts of the woods.",
    "12/25":"If it thunders, a movement of troops to war, but it will turn out well.",
    "12/26":"If it thunders, it threatens diseases for the slaves.",
    "12/27":"If it thunders, the king will help many.",
    "12/28":"If it thunders, the hatching of locusts.",
    "12/29":"If it thunders, it signifies the most healthful leanness for the bodies.",
    "12/30":"If it thunders, it signifies a rebellion against the kingdom and, reasonably, war.",

}

let grkCalendar = {
    "01/01":"",
    "01/02":"",
    "01/03":"",
    "01/04":"",
    "01/05":"",
    "01/06":"",
    "01/07":"",
    "01/08":"",
    "01/09":"",
    "01/10":"",
    "01/11":"",
    "01/12":"",
    "01/13":"",
    "01/14":"",
    "01/15":"",
    "01/16":"",
    "01/17":"",
    "01/18":"",
    "01/19":"",
    "01/20":"",
    "01/21":"",
    "01/22":"",
    "01/23":"",
    "01/24":"",
    "01/25":"",
    "01/26":"",
    "01/27":"",
    "01/28":"",
    "01/29":"",
    "01/30":"",
    "01/31":"",

    "02/01":"",
    "02/02":"",
    "02/03":"",
    "02/04":"",
    "02/05":"",
    "02/06":"",
    "02/07":"",
    "02/08":"",
    "02/09":"",
    "02/10":"",
    "02/11":"",
    "02/12":"",
    "02/13":"",
    "02/14":"",
    "02/15":"",
    "02/16":"",
    "02/17":"",
    "02/18":"",
    "02/19":"",
    "02/20":"",
    "02/21":"",
    "02/22":"",
    "02/23":"",
    "02/24":"",
    "02/25":"",
    "02/26":"",
    "02/27":"",
    "02/28":"",
    
    "03/01":"",
    "03/02":"",
    "03/03":"",
    "03/04":"",
    "03/05":"",
    "03/06":"",
    "03/07":"",
    "03/08":"",
    "03/09":"",
    "03/10":"",
    "03/11":"",
    "03/12":"",
    "03/13":"",
    "03/14":"",
    "03/15":"",
    "03/16":"",
    "03/17":"",
    "03/18":"",
    "03/19":"",
    "03/20":"",
    "03/21":"",
    "03/22":"",
    "03/23":"",
    "03/24":"",
    "03/25":"",
    "03/26":"",
    "03/27":"",
    "03/28":"",
    "03/29":"",
    "03/30":"",
    "03/31":"",

    "04/01":"",
    "04/02":"",
    "04/03":"",
    "04/04":"",
    "04/05":"",
    "04/06":"",
    "04/07":"",
    "04/08":"",
    "04/09":"",
    "04/10":"",
    "04/11":"",
    "04/12":"",
    "04/13":"",
    "04/14":"",
    "04/15":"",
    "04/16":"",
    "04/17":"",
    "04/18":"",
    "04/19":"",
    "04/20":"",
    "04/21":"",
    "04/22":"",
    "04/23":"",
    "04/24":"",
    "04/25":"",
    "04/26":"",
    "04/27":"",
    "04/28":"",
    "04/29":"",
    "04/30":"",

    "05/01":"",
    "05/02":"",
    "05/03":"",
    "05/04":"",
    "05/05":"",
    "05/06":"",
    "05/07":"",
    "05/08":"",
    "05/09":"",
    "05/10":"",
    "05/11":"",
    "05/12":"",
    "05/13":"",
    "05/14":"",
    "05/15":"",
    "05/16":"",
    "05/17":"",
    "05/18":"",
    "05/19":"",
    "05/20":"",
    "05/21":"",
    "05/22":"",
    "05/23":"",
    "05/24":"",
    "05/25":"",
    "05/26":"",
    "05/27":"",
    "05/28":"",
    "05/29":"",
    "05/30":"",
    "05/31":"",
    
    "06/01":"ἐὰν βροντήσῃ, τῶν καρπῶν εὐφορία ἔσται, ἐξῃρημένων κριθῶν· νοσήματα δὲ ἐπισφαλῆ τοῖς σώμασιν ἐπισκήψει.",
    "06/02":"",
    "06/03":"",
    "06/04":"",
    "06/05":"",
    "06/06":"",
    "06/07":"",
    "06/08":"",
    "06/09":"",
    "06/10":"",
    "06/11":"",
    "06/12":"",
    "06/13":"",
    "06/14":"",
    "06/15":"",
    "06/16":"",
    "06/17":"",
    "06/18":"",
    "06/19":"",
    "06/20":"",
    "06/21":"",
    "06/22":"", 
    "06/23":"",
    "06/24":"ἐὰν βροντήσῃ, εὐθηνίαν δηλοῖ.",
    "06/25":"ἐὰν βροντήσῃ, πόλεμοι καὶ μυρία ἔσονται κακά.",
    "06/26":"ἐὰν βροντήσῃ, ὁ χειμὼν τοῖς καρποῖς ἐπιβλαβὴς ἔσται",
    "06/27":"ἐὰν βροντήσῃ, κίνδυνος στρατιωτικὸς τοῖς κρατοῦσιν ἔσται.",
    "06/28":"ἐὰν βροντήσῃ, εὐετηρία ἔσται τῶν καρπῶν.",
    "06/29":"ἐὰν βροντήσῃ, τὰ τῆς βασιλίδος πόλεως ἔσται κρείττονα.",
    "06/30":"ἐὰν βροντήσῃ, πρὸς βραχὺ θάνατος ἔσται συχνός.",

    "07/01":"Ἐπὶ τῆς σεληνιακῆς νουμηνίας ἐὰν βροντήσῃ, εὐθηνία μὲν ἔσται, τῶν δὲ θρεμμάτων πτῶσις.",
    "07/02":"ἐὰν βροντήσῃ, καλὸν τῷ φθινοπώρῳ.",
    "07/03":"ἐὰν βροντήσῃ, χειμῶνα βαρὺν σημαίωει.",
    "07/04":"ἐὰν βροντήσῃ, ἀέριοι ἔσονται ταραχαί, ὡς ἐξ αὐτῶν σπάνιν γενέσθαι.",
    "07/05":"ἐὰν βροντήσῃ, εὐθηνία μὲν σίτου, ἄρχοντος δὲ ἀγαθοῦ πτῶσις ἔσται.",
    "07/06":"ἐὰν βροντήσῃ, νόσους θανατηφόρους ταῖς δουλικαῖς τύχαις ἀπειλεῖ.",
    "07/07":"ἐὰν βροντήσῃ, κατομβρία ἔσται βλαβερὰ τοῖς σπορίμοις.",
    "07/08":"ἐὰν βροντήσῃ, εἰρήνην μὲν τοῖς κοινοῖς, ὄλεθρον δὲ τοῖς βοσκήμασι καὶ βῆχα ξηρὸν ἐνσκῆψαι δηλοῖ.",
    "07/09":"ἐὰν βροντήσῃ, ἐποψίαν θεῶν καὶ ἀγαθῶν πολλῶν πρόσοδον δηλοῖ.",
    "07/10":"ἐὰν βροντήσῃ, σωτηριώδη ἔσται τὰ ποτάμια ὕδατα.",
    "07/11":"ἐὰν βροντήσῃ, καῦμα σημαίνει καὶ ὄμβρον βίαιον καὶ σπάνιν σίτου.",
    "07/12":"ἐὰν βροντήσῃ, ψῦχος τῷ θέρει ἔσται ἀδόκητον, δι’οὗ φθαρήσεται τὰ ἐπιτήδεια.",
    "07/13":"ἐὰν βροντήσῃ, ἑπρετὰ φανεῖται βλαβερώτατα.",
    "07/14":"ἐὰν βροντήσῃ, εἰς ἕνα τὴν πάντων δύναμιν ἐλθεῖν φράζει· οὗτος δὲ ἔσται τοῖς πράγμασιν ἀδικώτατος.",
    "07/15":"ἐὰν βροντήσῃ, διχόνοια ἔσται τοῦ δήμου καὶ τοῦ σίτου ἔνδεια.",
    "07/16":"ἐὰν βροντήσῃ, πόλεμον ὁ τῆς ἀνατολῆς βασιλεὺς ἐκδεχέσθω καὶ νόσον ἀπὸ ξηροῦ καύματος.",
    "07/17":"ἐὰν βροντήσῃ, διαδοχὴν μεγάλου ἄρχοντος δηλοῖ.",
    "07/18":"ἐὰν βροντήσῃ, ἔνδειαν καρπῶν ἐξ ἐπομβρίας ἀπειλεῖ.",
    "07/19":"ἐὰν βροντήσῃ, πόλεμον δηλοῖ καὶ ἀπώλειαν δυνατῶν· ἀφθονία δὲ ἔσται τῶν ξηρῶν καρπῶν.",
    "07/20":"ἐὰν βροντήσῃ, αὐχμὸν νοσώδη ἀπειλεῖ.",
    "07/21":"ἐὰν βροντήσῃ, διχόνοια ἔσται τοῖς ὑπηκόοις, ἀλλ’ οὐκ εἰς μακράν.",
    "07/22":"ἐὰν βροντήσῃ, ἀγαθὰ μὲν τοῖς κοινοῖς πράγμασι,νόσους δὲ τοῖς σώμασι περὶ τὴν κεφαλὴν σημαίνει.",
    "07/23":"ἐὰν βροντήσῃ, ἡ διχόνοια τοῦ δήμου παυθήσεται.",
    "07/24":"ἐὰν βροντήσῃ, δυνατοῦ ἀνθρώπου δηλοῖ δυνατὸν ἀτύχημα.",
    "07/25":"ἐὰν βροντήσῃ, τῇ νεολαίᾳ κάκωσις καὶ τοῖς καρποῖς μετ’ αὐτῆς, νοσώδης δὲ ὁ καιρὸς ἔσται.",
    "07/26":"ἐὰν βροντήσῃ, ἀπὸ μεγάλης εὐθηνίας ἔνδεια ἔσται.",
    "07/27":"ἐὰν βροντήσῃ, ἐκβρασμὸν τοῖς σώμασιν ἀπειλεῖ.",
    "07/28":"ἐὰν βροντήσῃ, ἔνδεια ὑδάτων καὶ ὄχλος ἑρπετῶν ἐπιβλαβῶν ἔσται.",
    "07/29":"ἐὰν βροντήσῃ, εὐετηρίαν δηλοῖ.",
    "07/30":"ἐὰν βροντήσῃ, οἱ ἄνθρωποι ἐκ ποινηλασίας ἐπὶ τὰ χείριστα τῶν πταισμάτων ὀλισθήσουσιν.",

    "08/01":"",
    "08/02":"",
    "08/03":"",
    "08/04":"",
    "08/05":"",
    "08/06":"",
    "08/07":"",
    "08/08":"",
    "08/09":"",
    "08/10":"",
    "08/11":"",
    "08/12":"",
    "08/13":"",
    "08/14":"",
    "08/15":"",
    "08/16":"",
    "08/17":"",
    "08/18":"",
    "08/19":"",
    "08/20":"",
    "08/21":"",
    "08/22":"",
    "08/23":"",
    "08/24":"",
    "08/25":"",
    "08/26":"",
    "08/27":"",
    "08/28":"",
    "08/29":"",
    "08/30":"",
    "08/31":"",
    
    "09/01":"",
    "09/02":"",
    "09/03":"",
    "09/04":"",
    "09/05":"",
    "09/06":"",
    "09/07":"",
    "09/08":"",
    "09/08":"",
    "09/09":"",
    "09/10":"",
    "09/11":"",
    "09/12":"",
    "09/13":"",
    "09/14":"",
    "09/15":"",
    "09/16":"",
    "09/17":"",
    "09/18":"",
    "09/19":"",
    "09/20":"",
    "09/21":"",
    "09/22":"",
    "09/23":"",
    "09/24":"",
    "09/25":"",
    "09/26":"",
    "09/27":"",
    "09/28":"",
    "09/29":"",
    "09/30":"",

    "10/01":"",
    "10/02":"",
    "10/03":"",
    "10/04":"",
    "10/05":"",
    "10/06":"",
    "10/07":"",
    "10/08":"",
    "10/09":"",
    "10/10":"",
    "10/11":"",
    "10/12":"",
    "10/13":"",
    "10/14":"",
    "10/15":"",
    "10/16":"",
    "10/17":"",
    "10/18":"",
    "10/19":"",
    "10/20":"",
    "10/21":"",
    "10/22":"",
    "10/23":"",
    "10/24":"",
    "10/25":"",
    "10/26":"",
    "10/27":"",
    "10/28":"",
    "10/29":"",
    "10/30":"",
    "10/31":"",
    
    "11/01":"",
    "11/02":"",
    "11/03":"",
    "11/04":"",
    "11/05":"",
    "11/06":"",
    "11/07":"",
    "11/08":"",
    "11/09":"",
    "11/10":"",
    "11/11":"",
    "11/12":"",
    "11/13":"",
    "11/14":"",
    "11/15":"",
    "11/16":"",
    "11/17":"",
    "11/18":"",
    "11/19":"",
    "11/20":"",
    "11/21":"",
    "11/22":"",
    "11/23":"",
    "11/24":"",
    "11/25":"",
    "11/26":"",
    "11/27":"",
    "11/28":"",
    "11/29":"",
    "11/30":"",

    "12/01":"",
    "12/02":"",
    "12/03":"",
    "12/04":"",
    "12/05":"",
    "12/06":"",
    "12/07":"",
    "12/08":"",
    "12/09":"",
    "12/10":"",
    "12/11":"",
    "12/12":"",
    "12/13":"",
    "12/14":"",
    "12/15":"",
    "12/16":"",
    "12/17":"",
    "12/18":"",
    "12/19":"",
    "12/20":"",
    "12/21":"",
    "12/22":"",
    "12/23":"",
    "12/24":"",
    "12/25":"",
    "12/26":"",
    "12/27":"",
    "12/28":"",
    "12/29":"",
    "12/30":"",
    "12/31":"",


}